#!/bin/bash

# Basic Configs
export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
export OF_SCREEN_H=2400
export OF_STATUS_H=80
export OF_STATUS_INDENT_LEFT=48
export OF_STATUS_INDENT_RIGHT=48
export OF_CLOCK_POS=1
export OF_ALLOW_DISABLE_NAVBAR=0
export FOX_DELETE_AROMAFM=1
export FOX_BUILD_TYPE="Beta"
export FOX_REMOVE_BASH=1





